const ActionTypes = {
  //CONNECTION
  CONNECTED: "CONNECTED",

  //USER
  SET_USER: "SET_USER",

  //ROOM
  JOIN_ROOM: "JOIN_ROOM",
  RECEIVED_CHAT_MESSAGE: "RECEIVE_CHAT_MESSAGE",
};

export default ActionTypes;