const ActionTypes = {
  //CONNECTION
  CONNECTED: "CONNECTED",
  USER_DATA_IN_PROGRESS: "USER_DATA_IN_PROGRESS",
  USER_DATA_SET: "USER_DATA_SET",

  //ROOM
  SET_REDIRECT_ROOM_ID: "SET_REDIRECT_ROOM_ID",
  JOIN_ROOM_IN_PROGRESS: "JOIN_ROOM_IN_PROGRESS",
  JOIN_ROOM: "JOIN_ROOM",
  RECEIVED_CHAT_MESSAGE: "RECEIVE_CHAT_MESSAGE",
  ROOM_STATE_RECEIVED: "ROOM_STATE_RECEIVED",
  CONNECTION_ERROR: "CONNECTION_ERROR",
  POP_CONNECTION_ERROR: "POP_CONNECTION_ERROR",
};

export default ActionTypes;